version: 2
jobs:
  test:
    docker:
      - image: node:lts-alpine
    working_directory: ~/kamil
    steps:
      - checkout
      # Save GraphQL Schema as an artifact
      - store_artifacts:
          path: schema.graphql
          destination: graphql-schema
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
